version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install --upgrade pydoc-markdown>=4.6.4
      - pip install --upgrade mkdocs>=1.4.2
      - pydoc-markdown
      - mv docs/content/* docs
      - rmdir docs/content
