version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install pydoc-markdown
      - pip install mkdocs==1.3.0
      - pydoc-markdown
      - mv docs/content/* docs
      - rmdir docs/content
