line-length = 79
exclude = ["_version.py"]
ignore = [
    "E501" # Line too long
]
# List of rules: https://beta.ruff.rs/docs/rules/
select = [
  "E",   # pycodestyle - default
  "F",   # pyflakes - default
  "I"    # isort
]

[isort]
known-local-folder = ["hdx"]
